### ISSUE TITLE
Features übetragen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/email_obfuscator#1]
es gibt bereits ein FOR-Addon
https://github.com/FriendsOfREDAXO/emailobfuscator/

Wenn es hier noch wesentliche Features gibt, die im anderen Addon fehlen, dann diese übertragen und hier archivieren.

**Comment by TobiasKrais** [comment]
Ist gemacht. Dieses Addon wird eingestellt.
